### ISSUE TITLE
Support avro spec v1.8.2

### ISSUE THREAD

**Issue by germanschnyder** [asyncapi/.github#6] opened 2020-08-21 07:12 UTC
#### Reason/Context
Lots of projects still use avro specification 1.8.2 for historical reasons and there are no major differences between 1.8.2 schema and 1.9.0 schema.

#### Description
We just need to add the right mimetypes and consider that in 1.8.2 there is no support for enum default and there is no uuid type.

**Comment by derberg** [comment] 2020-08-21 08:02
hi @germanschnyder, isn't this a duplicate of https://github.com/asyncapi/avro-schema-parser/issues/7 ?

**Comment by germanschnyder** [comment] 2020-08-21 08:09
It is, but after i created the first one i couldn't find anywhere so i thought i may have forgotten a "submit" button click...

**Closed** 2020-08-21 08:16 UTC
Labels: enhancement
